title: My Notes
description: These are my notes.
author: Celine Yuwono
github: https://github.com/celineyuwono
about: A Collection of My Notes
disqus_shortname: celineyuwono
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
  # - icon: fa-facebook
  #   link: "#"
  - icon: fa-twitter
    link: "https://twitter.com/celineyuwono/"
  - icon: fa-linkedin
    link: "https://www.linkedin.com/in/celineyuwono/"
  # - icon: fa-stack-exchange
  #   link: "#"
  - icon: fa-github
    link: "https://github.com/celineyuwono"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
  - text: Notes by Category
    url: /category/AWS
  - text: Search Notes
    url: /search/
  - text: About
    url: /about/
  # - text: My Projects
  #   url: /projects/
  # - text: XML Feed
  # url: /feed.xml

url: "https://celineyuwonodiary.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]
